### ISSUE TITLE
docs: tags: which ones are the newer ones?

### ISSUE THREAD

**Issue by listx** [anapsix/docker-alpine-java#19]
The README says

```
MAJOR TAGGING UPDATE

To allow selection of specific Java version, a major retagging is taking place. Old tags will remain for compatibility sake, but are no longer documented.
```

but it doesn't say which tags are preferred (new) vs the old ones. Am I right in assuming that `8u102b14` is the preferred new style of tags, but that `8` and `latest` are old and remain only for compatibility reasons?

**Comment by anapsix** [comment]
`:8`,`:7` and `:latest` are all valid, but are not "locked" to any specific Java version / patch set - i.e. depending on when you pull the `:8` tagged image, for example, you might end up with `8u102b14`, `8u112b15`, `8u121b13`, etc..
Well, `:7` no as much, since it's EOL and no more patches are released.

However specific `:8uXXXbYY` tags (such as `:8u102b14`, `:8u112b15`) will guarantee paricular MAJOR-MINOR-BUILD Java versions.

**Comment by anapsix** [comment]
README has been updated, hope it clarifies things
reopen with edit suggestions if you feel it's unclear

**Comment by listx** [comment]
Cool, thanks!
