### ISSUE TITLE
environment supports

### ISSUE THREAD

**Issue by lj19950508** [anapsix/docker-alpine-java#85]
images: anapsix/alpine-java:8_server-jre_unlimited

support for ENV   JAVA_OPTS ?
 use  docker-compose 
environment:
  - JAVA_OPTS= -Dserver.port =8081 , but it doesn't work

**Comment by anapsix** [comment]
While it's quite helpful to be able to specify JAVA_OPTS via environment variable, image produced by this repo is meant to serve as a base for applications requiring Java. Since one's startup script may differ greatly from another's, particular implementation is left up to end-user.
To achieve desired effect you could add `JAVA_OPTS` to your launch command.
For example:
```
environment:
  JAVA_OPTS: "-Dserver.port =8081"
command: java ${JAVA_OPTS} ...
```

**Comment by lj19950508** [comment]
copy that   ,  tks
